# Generated by Django 3.2.9 on 2023-09-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
