# Generated by Django 3.2.9 on 2023-09-17 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
